- hosts: all
  become: yes
  tasks:
    - name: create the 'cluster' user
      user: name=cluster append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'cluster' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'cluster ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the ubuntu user
      authorized_key: user=cluster key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
